//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beams.xamaX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUser", Namespace="http://xprema.net")]
    [System.SerializableAttribute()]
    public partial class SystemUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private System.Nullable<int> Person_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Person_ID {
            get {
                return this.Person_IDField;
            }
            set {
                if ((this.Person_IDField.Equals(value) != true)) {
                    this.Person_IDField = value;
                    this.RaisePropertyChanged("Person_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPermession", Namespace="http://xprema.net")]
    [System.SerializableAttribute()]
    public partial class UserPermession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<int> PermessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PermessionValueField;
        
        private System.Nullable<int> UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Beams.xamaX.SystemPermession SystemPermessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Beams.xamaX.SystemUser SystemUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> PermessionID {
            get {
                return this.PermessionIDField;
            }
            set {
                if ((this.PermessionIDField.Equals(value) != true)) {
                    this.PermessionIDField = value;
                    this.RaisePropertyChanged("PermessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PermessionValue {
            get {
                return this.PermessionValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PermessionValueField, value) != true)) {
                    this.PermessionValueField = value;
                    this.RaisePropertyChanged("PermessionValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Beams.xamaX.SystemPermession SystemPermession {
            get {
                return this.SystemPermessionField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemPermessionField, value) != true)) {
                    this.SystemPermessionField = value;
                    this.RaisePropertyChanged("SystemPermession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Beams.xamaX.SystemUser SystemUser {
            get {
                return this.SystemUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemUserField, value) != true)) {
                    this.SystemUserField = value;
                    this.RaisePropertyChanged("SystemUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemPermession", Namespace="http://xprema.net")]
    [System.SerializableAttribute()]
    public partial class SystemPermession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PermessionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PermessionDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PermessionName {
            get {
                return this.PermessionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PermessionNameField, value) != true)) {
                    this.PermessionNameField = value;
                    this.RaisePropertyChanged("PermessionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PermessionDescription {
            get {
                return this.PermessionDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PermessionDescriptionField, value) != true)) {
                    this.PermessionDescriptionField = value;
                    this.RaisePropertyChanged("PermessionDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IDSender", Namespace="http://xprema.net")]
    [System.SerializableAttribute()]
    public partial class IDSender : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhatsAppIDSenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaskeyField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private System.Nullable<int> User_IDField;
        
        private System.Nullable<int> Company_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] whatsAppImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhatsAppStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDSenderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutoReplayMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WhatsAppIDSender {
            get {
                return this.WhatsAppIDSenderField;
            }
            set {
                if ((object.ReferenceEquals(this.WhatsAppIDSenderField, value) != true)) {
                    this.WhatsAppIDSenderField = value;
                    this.RaisePropertyChanged("WhatsAppIDSender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Paskey {
            get {
                return this.PaskeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PaskeyField, value) != true)) {
                    this.PaskeyField = value;
                    this.RaisePropertyChanged("Paskey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Company_ID {
            get {
                return this.Company_IDField;
            }
            set {
                if ((this.Company_IDField.Equals(value) != true)) {
                    this.Company_IDField = value;
                    this.RaisePropertyChanged("Company_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] whatsAppImg {
            get {
                return this.whatsAppImgField;
            }
            set {
                if ((object.ReferenceEquals(this.whatsAppImgField, value) != true)) {
                    this.whatsAppImgField = value;
                    this.RaisePropertyChanged("whatsAppImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string WhatsAppStatus {
            get {
                return this.WhatsAppStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.WhatsAppStatusField, value) != true)) {
                    this.WhatsAppStatusField = value;
                    this.RaisePropertyChanged("WhatsAppStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string IDSenderStatus {
            get {
                return this.IDSenderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.IDSenderStatusField, value) != true)) {
                    this.IDSenderStatusField = value;
                    this.RaisePropertyChanged("IDSenderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AutoReplayMsg {
            get {
                return this.AutoReplayMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoReplayMsgField, value) != true)) {
                    this.AutoReplayMsgField = value;
                    this.RaisePropertyChanged("AutoReplayMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xprema.net", ConfigurationName="xamaX.XamaWhatsAppServiceSoap")]
    public interface XamaWhatsAppServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetServiceStatusResult from namespace http://xprema.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/GetServiceStatus", ReplyAction="*")]
        Beams.xamaX.GetServiceStatusResponse GetServiceStatus(Beams.xamaX.GetServiceStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/StartService", ReplyAction="*")]
        void StartService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/StopService", ReplyAction="*")]
        void StopService();
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://xprema.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/HelloWorld", ReplyAction="*")]
        Beams.xamaX.HelloWorldResponse HelloWorld(Beams.xamaX.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://xprema.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/UserLogin", ReplyAction="*")]
        Beams.xamaX.UserLoginResponse UserLogin(Beams.xamaX.UserLoginRequest request);
        
        // CODEGEN: Generating message contract since element name userToken from namespace http://xprema.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/GetUserPermession", ReplyAction="*")]
        Beams.xamaX.GetUserPermessionResponse GetUserPermession(Beams.xamaX.GetUserPermessionRequest request);
        
        // CODEGEN: Generating message contract since element name snd from namespace http://xprema.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/IDSenderSave", ReplyAction="*")]
        Beams.xamaX.IDSenderSaveResponse IDSenderSave(Beams.xamaX.IDSenderSaveRequest request);
        
        // CODEGEN: Generating message contract since element name IDSenderGetAllResult from namespace http://xprema.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/IDSenderGetAll", ReplyAction="*")]
        Beams.xamaX.IDSenderGetAllResponse IDSenderGetAll(Beams.xamaX.IDSenderGetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/IDSenderGetIDSenderCount", ReplyAction="*")]
        int IDSenderGetIDSenderCount();
        
        // CODEGEN: Generating message contract since element name userToken from namespace http://xprema.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xprema.net/LoadIDSenderToSend", ReplyAction="*")]
        Beams.xamaX.LoadIDSenderToSendResponse LoadIDSenderToSend(Beams.xamaX.LoadIDSenderToSendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceStatus", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.GetServiceStatusRequestBody Body;
        
        public GetServiceStatusRequest() {
        }
        
        public GetServiceStatusRequest(Beams.xamaX.GetServiceStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetServiceStatusRequestBody {
        
        public GetServiceStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceStatusResponse", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.GetServiceStatusResponseBody Body;
        
        public GetServiceStatusResponse() {
        }
        
        public GetServiceStatusResponse(Beams.xamaX.GetServiceStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class GetServiceStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetServiceStatusResult;
        
        public GetServiceStatusResponseBody() {
        }
        
        public GetServiceStatusResponseBody(string GetServiceStatusResult) {
            this.GetServiceStatusResult = GetServiceStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Beams.xamaX.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Beams.xamaX.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserLogin", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.UserLoginRequestBody Body;
        
        public UserLoginRequest() {
        }
        
        public UserLoginRequest(Beams.xamaX.UserLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class UserLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public UserLoginRequestBody() {
        }
        
        public UserLoginRequestBody(string user, string pwd) {
            this.user = user;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserLoginResponse", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.UserLoginResponseBody Body;
        
        public UserLoginResponse() {
        }
        
        public UserLoginResponse(Beams.xamaX.UserLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class UserLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Beams.xamaX.SystemUser UserLoginResult;
        
        public UserLoginResponseBody() {
        }
        
        public UserLoginResponseBody(Beams.xamaX.SystemUser UserLoginResult) {
            this.UserLoginResult = UserLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPermessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPermession", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.GetUserPermessionRequestBody Body;
        
        public GetUserPermessionRequest() {
        }
        
        public GetUserPermessionRequest(Beams.xamaX.GetUserPermessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class GetUserPermessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userToken;
        
        public GetUserPermessionRequestBody() {
        }
        
        public GetUserPermessionRequestBody(string userToken) {
            this.userToken = userToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPermessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPermessionResponse", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.GetUserPermessionResponseBody Body;
        
        public GetUserPermessionResponse() {
        }
        
        public GetUserPermessionResponse(Beams.xamaX.GetUserPermessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class GetUserPermessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Beams.xamaX.UserPermession> GetUserPermessionResult;
        
        public GetUserPermessionResponseBody() {
        }
        
        public GetUserPermessionResponseBody(System.Collections.Generic.List<Beams.xamaX.UserPermession> GetUserPermessionResult) {
            this.GetUserPermessionResult = GetUserPermessionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDSenderSaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDSenderSave", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.IDSenderSaveRequestBody Body;
        
        public IDSenderSaveRequest() {
        }
        
        public IDSenderSaveRequest(Beams.xamaX.IDSenderSaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class IDSenderSaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Beams.xamaX.IDSender snd;
        
        public IDSenderSaveRequestBody() {
        }
        
        public IDSenderSaveRequestBody(Beams.xamaX.IDSender snd) {
            this.snd = snd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDSenderSaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDSenderSaveResponse", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.IDSenderSaveResponseBody Body;
        
        public IDSenderSaveResponse() {
        }
        
        public IDSenderSaveResponse(Beams.xamaX.IDSenderSaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class IDSenderSaveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IDSenderSaveResult;
        
        public IDSenderSaveResponseBody() {
        }
        
        public IDSenderSaveResponseBody(bool IDSenderSaveResult) {
            this.IDSenderSaveResult = IDSenderSaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDSenderGetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDSenderGetAll", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.IDSenderGetAllRequestBody Body;
        
        public IDSenderGetAllRequest() {
        }
        
        public IDSenderGetAllRequest(Beams.xamaX.IDSenderGetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IDSenderGetAllRequestBody {
        
        public IDSenderGetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDSenderGetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDSenderGetAllResponse", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.IDSenderGetAllResponseBody Body;
        
        public IDSenderGetAllResponse() {
        }
        
        public IDSenderGetAllResponse(Beams.xamaX.IDSenderGetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class IDSenderGetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Beams.xamaX.IDSender> IDSenderGetAllResult;
        
        public IDSenderGetAllResponseBody() {
        }
        
        public IDSenderGetAllResponseBody(System.Collections.Generic.List<Beams.xamaX.IDSender> IDSenderGetAllResult) {
            this.IDSenderGetAllResult = IDSenderGetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadIDSenderToSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadIDSenderToSend", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.LoadIDSenderToSendRequestBody Body;
        
        public LoadIDSenderToSendRequest() {
        }
        
        public LoadIDSenderToSendRequest(Beams.xamaX.LoadIDSenderToSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class LoadIDSenderToSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userToken;
        
        public LoadIDSenderToSendRequestBody() {
        }
        
        public LoadIDSenderToSendRequestBody(string userToken) {
            this.userToken = userToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadIDSenderToSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadIDSenderToSendResponse", Namespace="http://xprema.net", Order=0)]
        public Beams.xamaX.LoadIDSenderToSendResponseBody Body;
        
        public LoadIDSenderToSendResponse() {
        }
        
        public LoadIDSenderToSendResponse(Beams.xamaX.LoadIDSenderToSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xprema.net")]
    public partial class LoadIDSenderToSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Beams.xamaX.IDSender> LoadIDSenderToSendResult;
        
        public LoadIDSenderToSendResponseBody() {
        }
        
        public LoadIDSenderToSendResponseBody(System.Collections.Generic.List<Beams.xamaX.IDSender> LoadIDSenderToSendResult) {
            this.LoadIDSenderToSendResult = LoadIDSenderToSendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XamaWhatsAppServiceSoapChannel : Beams.xamaX.XamaWhatsAppServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XamaWhatsAppServiceSoapClient : System.ServiceModel.ClientBase<Beams.xamaX.XamaWhatsAppServiceSoap>, Beams.xamaX.XamaWhatsAppServiceSoap {
        
        public XamaWhatsAppServiceSoapClient() {
        }
        
        public XamaWhatsAppServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XamaWhatsAppServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XamaWhatsAppServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XamaWhatsAppServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beams.xamaX.GetServiceStatusResponse Beams.xamaX.XamaWhatsAppServiceSoap.GetServiceStatus(Beams.xamaX.GetServiceStatusRequest request) {
            return base.Channel.GetServiceStatus(request);
        }
        
        public string GetServiceStatus() {
            Beams.xamaX.GetServiceStatusRequest inValue = new Beams.xamaX.GetServiceStatusRequest();
            inValue.Body = new Beams.xamaX.GetServiceStatusRequestBody();
            Beams.xamaX.GetServiceStatusResponse retVal = ((Beams.xamaX.XamaWhatsAppServiceSoap)(this)).GetServiceStatus(inValue);
            return retVal.Body.GetServiceStatusResult;
        }
        
        public void StartService() {
            base.Channel.StartService();
        }
        
        public void StopService() {
            base.Channel.StopService();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beams.xamaX.HelloWorldResponse Beams.xamaX.XamaWhatsAppServiceSoap.HelloWorld(Beams.xamaX.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Beams.xamaX.HelloWorldRequest inValue = new Beams.xamaX.HelloWorldRequest();
            inValue.Body = new Beams.xamaX.HelloWorldRequestBody();
            Beams.xamaX.HelloWorldResponse retVal = ((Beams.xamaX.XamaWhatsAppServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beams.xamaX.UserLoginResponse Beams.xamaX.XamaWhatsAppServiceSoap.UserLogin(Beams.xamaX.UserLoginRequest request) {
            return base.Channel.UserLogin(request);
        }
        
        public Beams.xamaX.SystemUser UserLogin(string user, string pwd) {
            Beams.xamaX.UserLoginRequest inValue = new Beams.xamaX.UserLoginRequest();
            inValue.Body = new Beams.xamaX.UserLoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pwd = pwd;
            Beams.xamaX.UserLoginResponse retVal = ((Beams.xamaX.XamaWhatsAppServiceSoap)(this)).UserLogin(inValue);
            return retVal.Body.UserLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beams.xamaX.GetUserPermessionResponse Beams.xamaX.XamaWhatsAppServiceSoap.GetUserPermession(Beams.xamaX.GetUserPermessionRequest request) {
            return base.Channel.GetUserPermession(request);
        }
        
        public System.Collections.Generic.List<Beams.xamaX.UserPermession> GetUserPermession(string userToken) {
            Beams.xamaX.GetUserPermessionRequest inValue = new Beams.xamaX.GetUserPermessionRequest();
            inValue.Body = new Beams.xamaX.GetUserPermessionRequestBody();
            inValue.Body.userToken = userToken;
            Beams.xamaX.GetUserPermessionResponse retVal = ((Beams.xamaX.XamaWhatsAppServiceSoap)(this)).GetUserPermession(inValue);
            return retVal.Body.GetUserPermessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beams.xamaX.IDSenderSaveResponse Beams.xamaX.XamaWhatsAppServiceSoap.IDSenderSave(Beams.xamaX.IDSenderSaveRequest request) {
            return base.Channel.IDSenderSave(request);
        }
        
        public bool IDSenderSave(Beams.xamaX.IDSender snd) {
            Beams.xamaX.IDSenderSaveRequest inValue = new Beams.xamaX.IDSenderSaveRequest();
            inValue.Body = new Beams.xamaX.IDSenderSaveRequestBody();
            inValue.Body.snd = snd;
            Beams.xamaX.IDSenderSaveResponse retVal = ((Beams.xamaX.XamaWhatsAppServiceSoap)(this)).IDSenderSave(inValue);
            return retVal.Body.IDSenderSaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beams.xamaX.IDSenderGetAllResponse Beams.xamaX.XamaWhatsAppServiceSoap.IDSenderGetAll(Beams.xamaX.IDSenderGetAllRequest request) {
            return base.Channel.IDSenderGetAll(request);
        }
        
        public System.Collections.Generic.List<Beams.xamaX.IDSender> IDSenderGetAll() {
            Beams.xamaX.IDSenderGetAllRequest inValue = new Beams.xamaX.IDSenderGetAllRequest();
            inValue.Body = new Beams.xamaX.IDSenderGetAllRequestBody();
            Beams.xamaX.IDSenderGetAllResponse retVal = ((Beams.xamaX.XamaWhatsAppServiceSoap)(this)).IDSenderGetAll(inValue);
            return retVal.Body.IDSenderGetAllResult;
        }
        
        public int IDSenderGetIDSenderCount() {
            return base.Channel.IDSenderGetIDSenderCount();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beams.xamaX.LoadIDSenderToSendResponse Beams.xamaX.XamaWhatsAppServiceSoap.LoadIDSenderToSend(Beams.xamaX.LoadIDSenderToSendRequest request) {
            return base.Channel.LoadIDSenderToSend(request);
        }
        
        public System.Collections.Generic.List<Beams.xamaX.IDSender> LoadIDSenderToSend(string userToken) {
            Beams.xamaX.LoadIDSenderToSendRequest inValue = new Beams.xamaX.LoadIDSenderToSendRequest();
            inValue.Body = new Beams.xamaX.LoadIDSenderToSendRequestBody();
            inValue.Body.userToken = userToken;
            Beams.xamaX.LoadIDSenderToSendResponse retVal = ((Beams.xamaX.XamaWhatsAppServiceSoap)(this)).LoadIDSenderToSend(inValue);
            return retVal.Body.LoadIDSenderToSendResult;
        }
    }
}
